config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__', include('debug_toolbar.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('recipes/', include('recipes.urls')),
    path('plans/', include('plans.urls')),
    path('shopping/', include('shopping.urls')),
    path('settings/', include('preferences.urls')),
]

pages/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('about/', views.AboutPageView.as_view(), name='about'),
]

plans/urls.py
from django.urls import path, include

from . import views

app_name = 'plans'

urlpatterns = [
    path('week_plan/', views.WeekPlanNavView.as_view(), name='week-plan-nav'),
    path('week_plan/<str:week_start>/', views.WeekPlanView.as_view(), name='week-plan'),
    path('week_plan/<str:week_start>/plan/<str:day>/<int:meal_id>', views.PlanDetailView.as_view(), name='plan-detail'),
    path('delete_recipe/<str:week_start>/<str:day>/<int:meal_id>/<int:recipe_id>/',
         views.PlanRecipeDeleteView.as_view(), name='plan-recipe-delete'),
    path('propagate_recipe/<str:week_start>/<str:day>/<int:meal_id>/<int:recipe_id>/',
         views.PlanRecipePropagateView.as_view(), name='plan-recipe-propagate'),
    path('week_plan_summary/<str:week_start>/', views.WeekPlanSummaryView.as_view(), name='week-plan-summary'),
    path('week_cook_summary/<str:week_start>/', views.WeekCookSummaryView.as_view(), name='week-cook-summary'),
]

recipes/urls.py
from django.urls import path, include

from . import views

app_name = 'recipes'

urlpatterns = [
    path('add_recipe/', views.RecipeAddView.as_view(), name='add-recipe'),
    path('cookbook/', views.RecipeListView.as_view(), name='recipe-list'),
    path('show_recipe/<int:idx>/', views.RecipeShowView.as_view(), name='show-recipe'),
    path('delete_recipe/<int:idx>/', views.RecipeDeleteView.as_view(), name='delete-recipe'),
    path('edit_recipe/<int:pk>/', views.RecipeEditView.as_view(), name='edit-recipe'),
]

shopping/urls.py
from django.urls import path, include

from . import views

app_name = 'shopping'

urlpatterns = [
    path('', views.ShoppingNavView.as_view(), name='shopping-nav'),
    path('shopping_list/<int:idx>/', views.ShoppingListView.as_view(), name='shopping-list'),
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

templates/partials/_menu.html
<nav class="navbar is-transparent mt-1 mb-5" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item is-handwriting is-logo" href="{% url 'home' %}">
            meal prep
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarMP">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarMP" class="navbar-menu">
        {% if user.is_authenticated %}
        <div class="navbar-start">
            <a class="navbar-item" aria-current="page" href="{% url 'plans:week-plan-nav' %}">planuj!</a>
            <a class="navbar-item" aria-current="page" href="{% url 'shopping:shopping-nav' %}">zakupy</a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link" aria-current="page" href="{% url 'recipes:recipe-list' %}">książka kucharska</a>

                <div class="navbar-dropdown">
                    <a class="navbar-item is-dropdown" aria-current="page" href="{% url 'recipes:add-recipe' %}">dodaj przepis</a>

                </div>
            </div>
             <a class="navbar-item" aria-current="page" href="{% url 'preferences:user-preferences' %}">ustawienia</a>
        {% endif %}
             <a class="navbar-item" aria-current="page"
                     {% if not user.is_authenticated %} id="white_about" {% endif %}
                href="{% url 'about' %}">o aplikacji</a>

        </div>

        <div class="navbar-end">
            <div class="navbar-item">
               <div class="buttons">
                   {% if user.is_authenticated %}
                    <a class="button is-light is-rounded" aria-current="page" href="{% url 'logout' %}">wyloguj</a>
                   {% else %}
                     <a class="button is-light is-rounded" aria-current="page" href="{% url 'login' %}">zaloguj</a>
                     <a class="button is-outlined is-rounded" aria-current="page" href="{% url 'users:signup' %}">
                       <strong>zarejestruj</strong>
                     </a>
                   {% endif %}
               </div>
            </div>
    </div>
  </div>
</nav>