config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__', include('debug_toolbar.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('recipes/', include('recipes.urls')),
    path('plans/', include('plans.urls')),
    path('shopping/', include('shopping.urls')),
    path('settings/', include('preferences.urls')),
]

pages/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('about/', views.AboutPageView.as_view(), name='about'),
]

shopping/urls.py
from django.urls import path, include

from . import views

app_name = 'shopping'

urlpatterns = [
    path('', views.ShoppingNavView.as_view(), name='shopping-nav'),
    path('shopping_list/<int:idx>/', views.ShoppingListView.as_view(), name='shopping-list'),
]

shopping/models.py
from django.db import models

from users.models import CustomUser


class ShoppingList(models.Model):
    date = models.DateField()
    products = models.TextField(null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['date', 'user']

    def __str__(self):
        return f'lista zakupowa użytkownika {self.user} na dzień {self.date}'

shopping/views.py
import json
from datetime import datetime

from django import views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

from plans.models import DayPlan
from shopping.models import ShoppingList


class ShoppingNavView(LoginRequiredMixin, views.View):
    """Shows next 5 shopping lists starting today"""
    def get(self, request):
        today = datetime.today()
        shopping_lists = ShoppingList.objects.filter(date__gte=today, user=request.user).order_by('date')[:5]

        return render(request, 'shopping/shopping_lists.html', {
            'shopping_lists': shopping_lists,
        })


class ShoppingListView(LoginRequiredMixin, views.View):
    """Shows shopping list details"""
    def get(self, request, idx):
        shopping_list = ShoppingList.objects.get(pk=idx)
        shopping_for = DayPlan.objects.filter(shopping_list__id=idx)
        shopping_list_ingredients = []
        for plan in shopping_for:
            shopping_list_ingredients.extend(json.loads(plan.recipe.ingredients))
        return render(request, 'shopping/shopping_list_details.html', {
            'shopping_list': shopping_list,
            'products': shopping_list_ingredients
        })

shopping/templates/shopping/shopping_list_details.html
{% extends '_base.html' %}

{% block title %}
    shopping navigation
{% endblock %}

{% block content %}

    <h1>zakupy do zrobienia - <span style="color:grey;">{{ shopping_list.date|date:'l, d E' }}</span></h1><br><br>
    <ul class="list-group list-group-flush">
      {% for product in products %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
        <p style="color: #404040;">{{ product }}</p>
        </li>
      {% empty %}
        <p>twoja lista jest pusta</p>
      {% endfor %}
    </ul><br><br>



{% endblock %}

shopping/templates/shopping/shopping_lists.html
{% extends '_base.html' %}

{% block title %}
    shopping navigation
{% endblock %}

{% block content %}

<div class="row row-cols-5 mt-5">
  {% for list in shopping_lists %}
  <div class="col">
    <a class="card text-center card-aubergine-link" style="width: auto;" href="{% url 'shopping:shopping-list' idx=list.id %}">
      <div class="card-body">
        <p class="card-text">{{ list.date|date:'d E Y' }}</p>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}