config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__', include('debug_toolbar.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('recipes/', include('recipes.urls')),
    path('plans/', include('plans.urls')),
    path('shopping/', include('shopping.urls')),
    path('settings/', include('preferences.urls')),
]

pages/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('about/', views.AboutPageView.as_view(), name='about'),
]

plans/urls.py
from django.urls import path, include

from . import views

app_name = 'plans'

urlpatterns = [
    path('week_plan/', views.WeekPlanNavView.as_view(), name='week-plan-nav'),
    path('week_plan/<str:week_start>/', views.WeekPlanView.as_view(), name='week-plan'),
    path('week_plan/<str:week_start>/plan/<str:day>/<int:meal_id>', views.PlanDetailView.as_view(), name='plan-detail'),
    path('delete_recipe/<str:week_start>/<str:day>/<int:meal_id>/<int:recipe_id>/',
         views.PlanRecipeDeleteView.as_view(), name='plan-recipe-delete'),
    path('propagate_recipe/<str:week_start>/<str:day>/<int:meal_id>/<int:recipe_id>/',
         views.PlanRecipePropagateView.as_view(), name='plan-recipe-propagate'),
    path('week_plan_summary/<str:week_start>/', views.WeekPlanSummaryView.as_view(), name='week-plan-summary'),
    path('week_cook_summary/<str:week_start>/', views.WeekCookSummaryView.as_view(), name='week-cook-summary'),
]

recipes/urls.py
from django.urls import path, include

from . import views

app_name = 'recipes'

urlpatterns = [
    path('add_recipe/', views.RecipeAddView.as_view(), name='add-recipe'),
    path('cookbook/', views.RecipeListView.as_view(), name='recipe-list'),
    path('show_recipe/<int:idx>/', views.RecipeShowView.as_view(), name='show-recipe'),
    path('delete_recipe/<int:idx>/', views.RecipeDeleteView.as_view(), name='delete-recipe'),
    path('edit_recipe/<int:pk>/', views.RecipeEditView.as_view(), name='edit-recipe'),
]

plans/models.py
from django.db import models

from preferences.models import MealSetting
from recipes.models import Recipe
from shopping.models import ShoppingList
from users.models import CustomUser


class DayPlan(models.Model):
    date = models.DateField()
    meal = models.ForeignKey(MealSetting, null=True, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, null=True, on_delete=models.CASCADE)
    is_cooked = models.BooleanField(default=False)
    portions_cooked = models.IntegerField(null=True)
    shopping_list = models.ForeignKey(ShoppingList, models.SET_NULL, null=True)
    is_eaten = models.BooleanField(default=False)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['date', 'meal', 'recipe', 'is_cooked', 'is_eaten']

    def __str__(self):
        return f'plan użytkownika {self.user.username} ' \
               f'na dzień {self.date}.' \
               f'Przepis: {self.recipe.id}'

recipes/models.py
from django.db import models

from users.models import CustomUser


class Recipe(models.Model):
    name = models.CharField(max_length=200, unique=True)
    portions = models.IntegerField()
    method = models.TextField(blank=True)
    ingredients = models.TextField()
    added_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date_added = models.DateField(auto_now_add=True)
    meal_tags = models.ManyToManyField("MealTag")

    def __str__(self):
        return self.name

MEAL_TAG_CHOICES = [
    (1, 'śniadanie'),
    (2, 'przekąska'),
    (3, 'obiad'),
    (4, 'kolacja'),
    (5, 'zupa'),
    (6, 'deser'),
    (7, 'na drogę'),
]

class MealTag(models.Model):
    meal_tag = models.CharField(max_length=60, choices=MEAL_TAG_CHOICES)

    def __str__(self):
        return self.meal_tag

plans/views.py
import json
from datetime import date, timedelta, datetime

from django import views
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError, transaction
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DeleteView

from plans.models import DayPlan
from preferences.models import MealSetting
from recipes.models import Recipe
from shopping.models import ShoppingList


def generate_7_days_of_week(week_start):
    """generate date ranges for later querying for recipes"""

    base = datetime.strptime(week_start, '%Y-%m-%d').date()
    return [base + timedelta(days=x) for x in range(7)]


def generate_9_days_of_week(week_start):
    """generate date ranges for later querying for recipes"""

    base = datetime.strptime(week_start, '%Y-%m-%d').date()
    return [base - timedelta(days=2) + timedelta(days=x) for x in range(9)]


class WeekPlanNavView(LoginRequiredMixin, views.View):
    """Navigation for planning. Shows current week and two following weeks"""
    login_url = reverse_lazy('login')

    def get(self, request):
        print(date.today())
        base = date.today() + timedelta(days=0-date.today().weekday())
        plan_dates = {
            'w1_start': base,
            'w1_end': base + timedelta(days=6),
            'w2_start': base + timedelta(days=7),
            'w2_end': base + timedelta(days=13),
            'w3_start': base + timedelta(days=14),
            'w3_end': base + timedelta(days=20),
        }

        return render(request, 'plans/week_plan_nav.html', {
            'plan_dates': plan_dates,
        })


class WeekPlanView(LoginRequiredMixin, views.View):
    """Show days of selected week, where user can add recipes to the meal plan."""

    login_url = reverse_lazy('login')

    def get(self, request, week_start):
        user = request.user
        day_today = datetime.today().date()

        # generate day list
        day_list = generate_7_days_of_week(week_start)

        # show list of meals set by the user
        meal_list = user.selected_meals.all()

        # get recipes planned for each day and each meal
        day_meal_plan = []
        for day in day_list:
            for meal in meal_list:
                day_meal_plan.append(DayPlan.objects.filter(
                    user=request.user,
                    date=day,
                    meal_id=meal.id,
                    is_eaten=True))

        return render(request, 'plans/week_plan.html', {
            'week_start': week_start,
            'day_list': day_list,
            'today': day_today,
            'meal_list': meal_list,
            'day_meal_plan': day_meal_plan,
        })


class PlanRecipeDeleteView(LoginRequiredMixin, views.View):
    """Hidden view for deleting recipes from plan"""
    def get(self, request, week_start, day, meal_id, recipe_id):
        meal_date = datetime.strptime(day, '%Y-%m-%d').date()
        recipe_to_delete = DayPlan.objects.get(date=meal_date, meal_id=meal_id, recipe_id=recipe_id, is_eaten=True)
        recipe_to_delete.delete()

        # get list of days for cooking week (9 days)
        day_list_9 = generate_9_days_of_week(week_start)

        # check if recipe is eaten during the week. If not - delete it from cooking list
        if not DayPlan.objects.filter(date__in=day_list_9, recipe_id=recipe_id, is_eaten=True):
            recipe_to_delete = DayPlan.objects.filter(date__in=day_list_9, recipe_id=recipe_id, is_cooked=True)
            recipe_to_delete.delete()
        return redirect('plans:week-plan', week_start=week_start)


class PlanRecipePropagateView(LoginRequiredMixin, views.View):
    """Hidden view for propagating recipes to the next day.
    If the recipe is already there - silently pass IntegrityError, ergo: do nothing"""

    def get(self, request, week_start, day, meal_id, recipe_id):
        meal_date = datetime.strptime(day, '%Y-%m-%d').date()
        meal_date_next = meal_date + timedelta(days=1)
        meal = MealSetting.objects.get(pk=meal_id)
        recipe = Recipe.objects.get(pk=recipe_id)

        try:
            with transaction.atomic():
                DayPlan.objects.create(date=meal_date_next, meal=meal, recipe=recipe, is_eaten=True, user=request.user)
                return redirect('plans:week-plan', week_start=week_start)
        except IntegrityError as e:
            return HttpResponse(status=204)


class PlanDetailView(LoginRequiredMixin, views.View):
    """Shows chosen meal in a chosen day and enables user to pick recipes.
    Creates initial cooking plan for the recipe"""

    def get(self, request, week_start, day, meal_id):
        meal = MealSetting.objects.get(pk=meal_id)
        meal_date = datetime.strptime(day, '%Y-%m-%d').date()

        already_chosen_recipes = DayPlan.objects.filter(date=meal_date, meal_id=meal_id, is_eaten=True)
        already_chosen_recipes_ids = []
        for recipe in already_chosen_recipes:
            already_chosen_recipes_ids.append(recipe.recipe_id)
        recipe_list = Recipe.objects.all().filter(added_by=request.user).exclude(pk__in=already_chosen_recipes_ids)

        return render(request, 'plans/plan_detail.html', {
            'meal_date': meal_date,
            'meal': meal,
            'recipe_list': recipe_list,
        })

    def post(self, request, week_start, day, meal_id):

        day_list_9 = generate_9_days_of_week(week_start)
        day_list_7 = generate_7_days_of_week(week_start)

        selected_recipes_ids = request.POST.getlist('recipes')
        selected_recipes = []
        for recipe_id in selected_recipes_ids:
            selected_recipes.append(Recipe.objects.get(pk=recipe_id))
        meal_date = datetime.strptime(day, '%Y-%m-%d').date()
        meal = MealSetting.objects.get(pk=meal_id)
        for recipe in selected_recipes:
            DayPlan.objects.create(date=meal_date, meal=meal, recipe=recipe, is_eaten=True, user=request.user)

            # check if this recipe has cooking_plan for the week.
            # if yes: check if the cooking_plan precedes first eating,
            # if not: create cooking_plan in the first day of eating

            first_eaten = DayPlan.objects.filter(
                date__in=day_list_7,
                recipe=recipe,
                is_eaten=True,
                user=request.user).order_by('date')[0]

            try:
                cooking_plan = DayPlan.objects.get(
                    date__in=day_list_9,
                    recipe=recipe,
                    is_cooked=True,
                    user=request.user)

                if cooking_plan.date > first_eaten.date:
                    cooking_plan.date = first_eaten.date
                    cooking_plan.save(update_fields=['date'])

            except ObjectDoesNotExist:
                DayPlan.objects.create(
                    date=first_eaten.date,
                    meal=meal,
                    recipe=recipe,
                    is_cooked=True,
                    user=request.user)

        return redirect(reverse('plans:week-plan', args=[week_start]))


def get_recipes_for_the_week(week_start, user):
    """get all eaten recipes for a given week"""

    # generate date ranges for later querying for recipes
    day_list_7 = generate_7_days_of_week(week_start)
    day_list_9 = generate_9_days_of_week(week_start)

    # get all recipes for the week, cooked and eaten
    weekly_plan = DayPlan.objects.filter(
        date__in=day_list_7, is_eaten=True, user=user
    ) | DayPlan.objects.filter(
        date__in=day_list_9, is_cooked=True, user=user
    ).order_by('recipe__name')

    recipe_list = {}
    for plan in weekly_plan:
        if plan.recipe not in recipe_list.keys():
            recipe_list[plan.recipe] = {'is_cooked': [], 'is_eaten': []}
        if plan.is_cooked:
            recipe_list[plan.recipe]['is_cooked'].append(plan.date)
            recipe_list[plan.recipe]['portions_cooked'] = plan.portions_cooked
        if plan.is_eaten:
            recipe_list[plan.recipe]['is_eaten'].append(plan.date)

    return day_list_9, recipe_list


class WeekPlanSummaryView(LoginRequiredMixin, views.View):
    """Table view of all recipes planned for the week.
    Here user can decide when to cook them and how many portions to cook for the week"""

    def get(self, request, week_start):
        day_list_9, recipe_list = get_recipes_for_the_week(week_start, user=request.user)
        return render(request, 'plans/week_plan_summary.html', {
            'day_list_9': day_list_9,
            'recipe_list': recipe_list,
        })

    def post(self, request, week_start):
        day_list_9, recipe_list = get_recipes_for_the_week(week_start, user=request.user)

        # updating cooking plans and portions cooked
        for recipe, dates in recipe_list.items():
            cooking_date = datetime.strptime(request.POST.get(f'{recipe.id}_cooked'), '%Y-%m-%d').date()
            cooking_portions = request.POST.get(f'{recipe.id}_portions')

            recipe_cooking_plan = DayPlan.objects.get(
                date__in=day_list_9,
                recipe=recipe,
                is_cooked=True,
                user=request.user)

            recipe_cooking_plan.date = cooking_date
            recipe_cooking_plan.portions_cooked = cooking_portions
            recipe_cooking_plan.save()

        return redirect(reverse('plans:week-cook-summary', args=[week_start]))


class WeekCookSummaryView(LoginRequiredMixin, views.View):
    """summary view for cooking plans - shows when to cook what"""
    def get(self, request, week_start):
        day_list_9 = generate_9_days_of_week(week_start)
        cooking_plans = DayPlan.objects.filter(date__in=day_list_9, is_cooked=True, user=request.user)

plans/templates/plans/plan_detail.html
{% extends '_base.html' %}

{% block title %}
    {{ meal.meal_name }} - {{ day }}
{% endblock %}

{% block content %}
    <div class="mb-4">
    <h1>{{ meal.meal_name }}</h1>
        <span style="color:grey;">
            <strong>{{ meal_date|date:'l' }}</strong> {{ meal_date|date:'d E' }}</span>
    </div>
    {% if recipe_list %}
    <form method="post">
    {% csrf_token %}

        <ul class="list-group list-group-flush">
            {% for recipe in recipe_list %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                <label>
                    <input type="checkbox" value="{{ recipe.id }}" name="recipes"> {{ recipe.name }}
                </label>
                </li>
            {% endfor %}
        </ul>
        <button type="submit" class="btn btn-aubergine mt-4">zapisz</button>
    </form>

    {% else %}
        Dodaj przepisy do swojej książki kucharskiej, żeby móc planować posiłki<br>
        <a href="{% url 'recipes:add-recipe' %}" class="btn btn-aubergine">dodaj przepis</a>

    {% endif %}
{% endblock %}

plans/templates/plans/week_cook_summary.html
{% extends '_base.html' %}

{% block title %}
    plan gotowania
{% endblock %}

{% block content %}

<div class="mb-5">
<h3>Zaplanuj dni zakupowe:</h3>
<ol>
    <li>zaznacz, w które dni wybierzesz się na zakupy</li>
</ol>
</div>

<form method="post">
{% csrf_token %}

<ul class="list-group list-group-flush">
{% for day in day_list %}

    <li class="list-group-item mb-4">
        <div>
        <div style="background-color:yellow;" class="mb-4"><strong>{{ day|date:'l' }}</strong> <span style="color:grey;">{{ day|date:'d E' }}</span>
        </div>
        <span class="btn-multichoice btn-multichoice-sm" style="width: fit-content">
           <label>
              <input type="checkbox" value="{{ day|date:'Y-m-d' }}" name="do_shopping"><span>zakupy</span>
           </label>
        </span>


            <ul class="list-group list-group-flush">
                {% for plan in cooking_plans %}
                    {% if plan.date == day %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="col"><strong>{{ plan.recipe }}</strong></div>
                    <div class="col">porcje: {{ plan.portions_cooked }}</div>
                    <a href="{% url 'recipes:show-recipe' idx=plan.recipe_id %}" class="col btn btn-aubergine">zobacz przepis</a>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>

    </li>

{% endfor %}
</ul>

<div class="row mb-5">
<button type="submit" class="btn btn-aubergine">zapisz</button>
</div>
</form>
{% endblock %}

plans/templates/plans/week_plan.html
{% extends '_base.html' %}

{% block title %}
    planowanie tygodnia
{% endblock %}

{% block content %}

<ul class="list-group list-group-flush">
{% for day in day_list %}

    <li class="list-group-item mb-4">
        <div>
        <div style="background-color:yellow;" class="mb-4"><strong>{{ day|date:'l' }}</strong> <span style="color:grey;">{{ day|date:'d E' }}</span></div>

            <ul class="list-group list-group-flush">
                {% for meal in meal_list %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <strong>{{ meal.meal_name }}</strong>
                    {% if day >= today %}
                    <span><a href="{% url 'plans:plan-detail' week_start=week_start day=day meal_id=meal.id %}" class="btn btn-aubergine">+</a></span>
                    {% endif %}
                    </li>
                        <div class="ms-4 me-5">
                        <ul class="list-group list-group-flush">
                        {% for plan in day_meal_plan %}
                                {% for item in plan %}
                                    {% if item.date == day and item.meal.meal_name == meal.meal_name %}
                                        <li class="list-group-item d-flex justify-content-between align-items-start">
                                        <span>
                                        <a class="list-group-item-action" style="text-decoration: none;"
                                           href="{% url 'recipes:show-recipe' idx=item.recipe.id %}">
                                            {{ item.recipe.name }}
                                        </a></span>
                                        <span>
                                        <a href="{% url 'plans:plan-recipe-propagate' week_start=week_start day=day meal_id=item.meal.id recipe_id=item.recipe.id %}" style="text-decoration: none;">&#11015;</a>
                                        {% if day >= today %}
                                            <a href="{% url 'plans:plan-recipe-delete' week_start=week_start day=day meal_id=item.meal.id recipe_id=item.recipe.id %}" style="text-decoration: none;">&#128465;</a>
                                        {% endif %}
                                        </span>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                        {% empty %}
                        {% endfor %}
                        </ul>
                        </div>
                    <div class="mb-4"></div>

                {% endfor %}
            </ul>
        </div>

    </li>

{% endfor %}
</ul>

<div class="row mb-5">
<a href="{% url 'plans:week-plan-summary' week_start=week_start %}" class="btn btn-aubergine">dalej</a>
</div>

{% endblock %}

plans/templates/plans/week_plan_nav.html
{% extends '_base.html' %}

{% block title %}
    plans navigation
{% endblock %}

{% block content %}

<div class="row row-cols-3 mt-5">
  <div class="col">
    <a class="card text-center card-aubergine-link-active" href="{% url 'plans:week-plan' week_start=plan_dates.w1_start %}">
      <div class="card-body">
        <h5 class="card-title">aktualny tydzień</h5>
        <p class="card-text">{{ plan_dates.w1_start|date:'d E Y' }}</p>
        <p class="card-text">*</p>
        <p class="card-text">{{ plan_dates.w1_end|date:'d E Y' }}</p>
      </div>
    </a>
  </div>
  <div class="col">
    <a class="card text-center card-aubergine-link" href="{% url 'plans:week-plan' week_start=plan_dates.w2_start %}">
      <div class="card-body">
        <h5 class="card-title">następny tydzień</h5>
        <p class="card-text">{{ plan_dates.w2_start|date:'d E Y' }}</p>
        <p class="card-text">*</p>
        <p class="card-text">{{ plan_dates.w2_end|date:'d E Y' }}</p>
      </div>
    </a>
  </div>
  <div class="col">
    <a class="card text-center card-aubergine-link" href="{% url 'plans:week-plan' week_start=plan_dates.w3_start %}">
      <div class="card-body">
        <h5 class="card-title">za dwa tygodnie</h5>
        <p class="card-text">{{ plan_dates.w3_start|date:'d E Y' }}</p>
        <p class="card-text">*</p>
        <p class="card-text">{{ plan_dates.w3_end|date:'d E Y' }}</p>
      </div>
    </a>
  </div>
</div>
{% endblock %}

plans/templates/plans/week_plan_summary.html
{% extends '_base.html' %}

{% block title %}
    planowanie tygodnia
{% endblock %}

{% block content %}

<div class="mb-5">
<h3>Dokończ planowanie podejmując kolejne decyzje:</h3>
<ol>
    <li>dla każdego dania wpisz liczbę porcji, której potrzebujesz w całym tygodniu</li>
    <li>dla każdego dania zaznacz, kiedy planujesz go ugotować</li>
</ol>
    <hr>
    <div class="row" style="width: 50%;">
        <div class="col">&#129000; jedzenie</div>
        <div class="col">&#128997; gotowanie</div>
        <div class="col">&#129003; gotowanie i jedzenie</div>
    </div>
</div>


<form method="post">
{% csrf_token %}

<table class="table">
  <thead class="table-warning" style="text-align: center;">
    <tr>
      <th scope="col"> </th>
      {% for day in day_list_9 %}
      <th scope="col" style="font-weight: normal;">{{ day|date:'d.m' }}</th>
      {% endfor %}
      <th scope="col">porcje</th>
      <th scope="col">gotowanie</th>
    </tr>
  </thead>

  <tbody>
  {% for recipe, plan in recipe_list.items %}
    <tr>
      <th scope="row" style="text-align: right;">{{ recipe }}</th>
      {% for day in day_list_9 %}
          {% if day in plan.is_eaten and day not in plan.is_cooked%}
              <td style="text-align: center;">&#129000;</td>
          {% elif day not in plan.is_eaten and day in plan.is_cooked%}
              <td style="text-align: center;">&#128997;</td>
          {% elif day in plan.is_eaten and day in plan.is_cooked%}
              <td style="text-align: center;">&#129003;</td>
          {% else %}
              <td></td>
          {% endif %}
      {% endfor %}
      <td style="text-align: center;">
          <label>
              <input name="{{ recipe.id }}_portions" type="number" min="1" max="15" step="0.5" value="{{ plan.portions_cooked }}"
                      style="width: 50px;" required>
          </label>
      </td>
      <td style="text-align: center;">
          <label>
              <input name="{{ recipe.id }}_cooked" type="date" value="{{ plan.is_cooked.0|date:'Y-m-d' }}" required>
          </label>
      </td>
    </tr>
  {% endfor %}

  </tbody>
</table>

    <div class="row mt-5"><button type="submit" class="btn btn-aubergine">zapisz</button></div>
</form>
{% endblock %}